openprocurement/openprocurement.tender.competitivedialogue

- openprocurement/tender/competitivedialogue/models.py
- openprocurement/tender/competitivedialogue/tests/base.py
- openprocurement/tender/competitivedialogue/tests/bid.py
- openprocurement/tender/competitivedialogue/tests/lot.py
- openprocurement/tender/competitivedialogue/tests/tender.py
- openprocurement/tender/competitivedialogue/utils.py
Два нові статуси, логіку описували тут https://groups.google.com/forum/#!msg/open-procurement-dev/Pwb_usMTZK8/9ZusnBSjAgAJ
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openprocurement/openprocurement.tender.competitivedialogue/4)
> Add new statuses active.waiting-stage2 and active.ready-stage2

- openprocurement/tender/competitivedialogue/__init__.py
- openprocurement/tender/competitivedialogue/models.py
- openprocurement/tender/competitivedialogue/utils.py
- openprocurement/tender/competitivedialogue/views/tender.py
- setup.py
Добавлена логіка по другому етапу (model та views)
Залежить (поки) від 
https://github.com/openprocurement/openprocurement.api/pull/96
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openprocurement/openprocurement.tender.competitivedialogue/8)
> add stage2 model and views

- openprocurement/tender/competitivedialogue/tests/bid.py
- openprocurement/tender/competitivedialogue/tests/lot.py
- openprocurement/tender/competitivedialogue/utils.py
За умовою ТЗ потрібно, щоб кількість пропозицію було не менше 3, для переходу на кваліфікації.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openprocurement/openprocurement.tender.competitivedialogue/10)
> Increase minimal number of bits

- openprocurement/tender/competitivedialogue/databridge.py
- openprocurement/tender/competitivedialogue/journal_msg_ids.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openprocurement/openprocurement.tender.competitivedialogue/11)
> Rewrite tender stage 2 if it stats in rewrite_statuses

- openprocurement/tender/competitivedialogue/models.py
- openprocurement/tender/competitivedialogue/tests/base.py
- openprocurement/tender/competitivedialogue/tests/cancellation.py
- openprocurement/tender/competitivedialogue/tests/complaint.py
- openprocurement/tender/competitivedialogue/tests/lot.py
- openprocurement/tender/competitivedialogue/tests/question.py
- openprocurement/tender/competitivedialogue/tests/tender.py
make minimalStep for tender and lot NOT required, and hide them in response.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openprocurement/openprocurement.tender.competitivedialogue/12)
> make minimalStep for tender and lot NOT required

- openprocurement/tender/competitivedialogue/models.py
- openprocurement/tender/competitivedialogue/tests/lot.py
- openprocurement/tender/competitivedialogue/tests/tender.py
- openprocurement/tender/competitivedialogue/utils.py
Не виконуються перевірки:
Контроль неперевищення ваги нецінових показників значення 30%
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openprocurement/openprocurement.tender.competitivedialogue/14)
> Control excess 30 percent

- openprocurement/tender/competitivedialogue/utils.py
- openprocurement/tender/competitivedialogue/views/stage2/bid.py
- openprocurement/tender/competitivedialogue/views/stage2/bid_document.py
Поки без покриття тестами із-за проблем з пам'яттю https://github.com/openprocurement/openprocurement.tender.competitivedialogue/pull/16
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openprocurement/openprocurement.tender.competitivedialogue/17)
> Add bid views

- openprocurement/tender/competitivedialogue/views/stage2/contract.py
- openprocurement/tender/competitivedialogue/views/stage2/contract_document.py
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openprocurement/openprocurement.tender.competitivedialogue/18)
> Add contract views

- openprocurement/tender/competitivedialogue/views/stage2/auction.py
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openprocurement/openprocurement.tender.competitivedialogue/19)
> add auction views

- openprocurement/tender/competitivedialogue/views/stage2/award.py
- openprocurement/tender/competitivedialogue/views/stage2/award_complaint.py
- openprocurement/tender/competitivedialogue/views/stage2/award_complaint_document.py
- openprocurement/tender/competitivedialogue/views/stage2/award_document.py
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openprocurement/openprocurement.tender.competitivedialogue/20)
> add award views

- openprocurement/tender/competitivedialogue/views/stage2/tender_document.py
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openprocurement/openprocurement.tender.competitivedialogue/21)
> add tender document views

- openprocurement/tender/competitivedialogue/views/stage2/question.py
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openprocurement/openprocurement.tender.competitivedialogue/22)
> add question views

- openprocurement/tender/competitivedialogue/views/stage2/qualification.py
- openprocurement/tender/competitivedialogue/views/stage2/qualification_complaint.py
- openprocurement/tender/competitivedialogue/views/stage2/qualification_complaint_document.py
- openprocurement/tender/competitivedialogue/views/stage2/qualification_document.py
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openprocurement/openprocurement.tender.competitivedialogue/23)
> add qualification views

- openprocurement/tender/competitivedialogue/views/stage2/cancellation.py
- openprocurement/tender/competitivedialogue/views/stage2/cancellation_document.py
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openprocurement/openprocurement.tender.competitivedialogue/24)
> add cancellation and cancellation_document views

- openprocurement/tender/competitivedialogue/views/stage2/complaint.py
- openprocurement/tender/competitivedialogue/views/stage2/complaint_document.py
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openprocurement/openprocurement.tender.competitivedialogue/25)
> add complaint and complaint_document views

- openprocurement/tender/competitivedialogue/databridge.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openprocurement/openprocurement.tender.competitivedialogue/26)
> remove generate new id for lots and itens

- openprocurement/tender/competitivedialogue/views/stage2/lot.py
Дозволено редагування лотів у статусі draft.stage2
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openprocurement/openprocurement.tender.competitivedialogue/27)
> edit lots in draft.stage2 status

- openprocurement/tender/competitivedialogue/views/stage2/tender_document.py
Можливість завантажувати документи у draft.stage2 статусі
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openprocurement/openprocurement.tender.competitivedialogue/28)
> upload documents in draft.stage2 status

- openprocurement/tender/competitivedialogue/databridge.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openprocurement/openprocurement.tender.competitivedialogue/31)
> copy features in stage2

- openprocurement/tender/competitivedialogue/models.py
- openprocurement/tender/competitivedialogue/tests/base.py
Мінімальна кількість елементів  shortedlistedFirms повина бути 3.
Якщо в shortedlistedFirms є посилання на id лота, то цей лот повинен обов'язково бути в tender.lots
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openprocurement/openprocurement.tender.competitivedialogue/32)
> Валідація shortlistedFirms

- openprocurement/tender/competitivedialogue/tests/stage1/tender.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openprocurement/openprocurement.tender.competitivedialogue/33)
> try send minimaStep for stage1

- openprocurement/tender/competitivedialogue/models.py
- openprocurement/tender/competitivedialogue/tests/stage2/tender.py
Додана валідація згідно ТЗ https://docs.google.com/document/d/1fYp31JAS1b_x9RF2RMUqoqL1DhuqDgmUAGMU-9rPXh8/edit#heading=h.dx9bmnjffqp9
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openprocurement/openprocurement.tender.competitivedialogue/34)
> Заборона змінювати нецінові показники

- openprocurement/tender/competitivedialogue/models.py
- openprocurement/tender/competitivedialogue/tests/base.py
- openprocurement/tender/competitivedialogue/tests/stage2/lot.py
- openprocurement/tender/competitivedialogue/views/stage2/contract.py
Додав тести для лотів другого етапу.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openprocurement/openprocurement.tender.competitivedialogue/35)
> Add tests lot stage2

- openprocurement/tender/competitivedialogue/models.py
- openprocurement/tender/competitivedialogue/tests/base.py
- openprocurement/tender/competitivedialogue/tests/stage2/lot.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openprocurement/openprocurement.tender.competitivedialogue/36)
> Add tests lot stage2 ua

- openprocurement/tender/competitivedialogue/models.py
- openprocurement/tender/competitivedialogue/tests/base.py
- openprocurement/tender/competitivedialogue/tests/stage1/lot.py
- openprocurement/tender/competitivedialogue/tests/stage1/tender.py
Після обнови ТЗ, було вирішено зробити minimalStep обов'язковим.
Додав можливість встановлювати minimalStep на першому етапі та зробив його обов'язковим, поправив ролі для першого етапу
Унаслідував лот від базової моделі.
> minimalStep required

- openprocurement/tender/competitivedialogue/models.py
- openprocurement/tender/competitivedialogue/tests/stage2/lot.py
- openprocurement/tender/competitivedialogue/tests/stage2/tender.py
обмеження по неціновим зробити 99%. Тобто, ціна має складати мінімум 1%
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openprocurement/openprocurement.tender.competitivedialogue/38)
> make max 99% sum of features for stage2 

- openprocurement/tender/competitivedialogue/models.py
- openprocurement/tender/competitivedialogue/tests/base.py
- openprocurement/tender/competitivedialogue/tests/stage2/lot.py
- openprocurement/tender/competitivedialogue/tests/stage2/tender.py
- openprocurement/tender/competitivedialogue/validation.py
- openprocurement/tender/competitivedialogue/views/stage2/lot.py
Замовник не має право редагувати лоти на другому етапі
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openprocurement/openprocurement.tender.competitivedialogue/41)
> Close lots on stage2

- openprocurement/tender/competitivedialogue/models.py
- openprocurement/tender/competitivedialogue/tests/stage1/lot.py
- openprocurement/tender/competitivedialogue/tests/stage1/tender.py
Валідація значення по одному неціновому показнику змінена з 0.3 до 0.99
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openprocurement/openprocurement.tender.competitivedialogue/43)
> single feature value up to 0.99

- openprocurement/tender/competitivedialogue/tests/stage2/cancellation.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openprocurement/openprocurement.tender.competitivedialogue/44)
> Add tests for cancellation

- openprocurement/tender/competitivedialogue/tests/stage2/document.py
Add tests for documents views stage2
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openprocurement/openprocurement.tender.competitivedialogue/45)
> add tests for documents

- openprocurement/tender/competitivedialogue/models.py
- openprocurement/tender/competitivedialogue/tests/base.py
- openprocurement/tender/competitivedialogue/tests/stage2/complaint.py
- openprocurement/tender/competitivedialogue/tests/stage2/lot.py
- openprocurement/tender/competitivedialogue/utils.py
- openprocurement/tender/competitivedialogue/validation.py
- openprocurement/tender/competitivedialogue/views/stage2/complaint.py
Подавати вимоги про усунення порушення, скарги можуть лише ті учасники, які були допущені до переговорів на першому етапі.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openprocurement/openprocurement.tender.competitivedialogue/42)
> Validate complaints

- openprocurement/tender/competitivedialogue/databridge.py
Якщо перший етап був прискореним, то другий має бути прискореним теж
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openprocurement/openprocurement.tender.competitivedialogue/47)
> copy procurementMethodDetails if it's exists

- openprocurement/tender/competitivedialogue/tests/stage2/question.py
- openprocurement/tender/competitivedialogue/tests/stage2/tender.py
- openprocurement/tender/competitivedialogue/utils.py
- openprocurement/tender/competitivedialogue/validation.py
- openprocurement/tender/competitivedialogue/views/stage2/question.py
Тільки учасник який був допущений до переговорів може задавати питання, по тендеру або по лоту
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openprocurement/openprocurement.tender.competitivedialogue/48)
> Validate post questions

- openprocurement/tender/competitivedialogue/tests/stage2/bid.py
- openprocurement/tender/competitivedialogue/tests/stage2/complaint.py
- openprocurement/tender/competitivedialogue/utils.py
- openprocurement/tender/competitivedialogue/views/stage2/bid.py
Додав тести для другого етапу.
Додав allowed_bid_status_on_create для вьюх
Owner не може зміни тендер, тому прибрав invalidate_bids_data
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openprocurement/openprocurement.tender.competitivedialogue/50)
> Add tests for bid stage2

- openprocurement/tender/competitivedialogue/tests/base.py
- openprocurement/tender/competitivedialogue/tests/stage2/auction.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openprocurement/openprocurement.tender.competitivedialogue/51)
> Add autcion test

- openprocurement/tender/competitivedialogue/tests/base.py
- openprocurement/tender/competitivedialogue/tests/stage2/award.py
- openprocurement/tender/competitivedialogue/views/stage2/award_complaint.py
- openprocurement/tender/competitivedialogue/views/stage2/award_document.py
Написав тести для awards, поправив баги які пов'язані з іменами views
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openprocurement/openprocurement.tender.competitivedialogue/53)
> Add test awards

- openprocurement/tender/competitivedialogue/tests/stage2/award.py
З прошлого пулу пройшов поламаний тест
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openprocurement/openprocurement.tender.competitivedialogue/54)
> Поправив тест з award

- openprocurement/tender/competitivedialogue/tests/stage2/chronograph.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openprocurement/openprocurement.tender.competitivedialogue/55)
> add tests for chronograph UA EU

- openprocurement/tender/competitivedialogue/tests/base.py
- openprocurement/tender/competitivedialogue/tests/stage2/contract.py
- openprocurement/tender/competitivedialogue/tests/stage2/lot.py
Додав тести для контрактів
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openprocurement/openprocurement.tender.competitivedialogue/56)
> add tests for contract

- openprocurement/tender/competitivedialogue/tests/stage2/qualification.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openprocurement/openprocurement.tender.competitivedialogue/57)
> add tests for EU

- openprocurement/tender/competitivedialogue/views/stage1/qualification_complaint_document.py
Помилково імпортнув неправильний клас
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openprocurement/openprocurement.tender.competitivedialogue/58)
> fix import

- openprocurement/tender/competitivedialogue/tests/stage1/bid.py
- openprocurement/tender/competitivedialogue/tests/stage1/lot.py
- openprocurement/tender/competitivedialogue/tests/stage1/tender.py
- openprocurement/tender/competitivedialogue/utils.py
Для проходження першого етапу необхідно 3 унікальних постачальника.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openprocurement/openprocurement.tender.competitivedialogue/62)
> add validation for unique bids identifier, fix tests

- openprocurement/tender/competitivedialogue/models.py
Якщо перший етап був запущений з procurementMethodDetails то на другому потрібно це враховувати.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openprocurement/openprocurement.tender.competitivedialogue/65)
> Додав initialize

- openprocurement/tender/competitivedialogue/databridge.py
- openprocurement/tender/competitivedialogue/models.py
Смержити після #65
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openprocurement/openprocurement.tender.competitivedialogue/66)
> Add fields

- buildout.cfg
- openprocurement/tender/competitivedialogue/tests/stage1/complaint.py
- openprocurement/tender/competitivedialogue/tests/stage2/award.py
- openprocurement/tender/competitivedialogue/tests/stage2/complaint.py
- openprocurement/tender/competitivedialogue/tests/stage2/qualification.py
- openprocurement/tender/competitivedialogue/utils.py
Після змін гілки master у openua(https://github.com/openprocurement/openprocurement.tender.openua/commit/c0c0d67cdc27c31c0795060e2ba48cba49e3681a) подальша сумісна робота гілок master та production неможлива.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openprocurement/openprocurement.tender.competitivedialogue/63)
> Виправлення гілки master

- openprocurement/tender/competitivedialogue/models.py
Ці зміни потрібні
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openprocurement/openprocurement.tender.competitivedialogue/67)
> Fix accelerator

- openprocurement/tender/competitivedialogue/databridge.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openprocurement/openprocurement.tender.competitivedialogue/68)
> copy submissionMethodDetails when debug mode

- openprocurement/tender/competitivedialogue/models.py
- openprocurement/tender/competitivedialogue/tests/stage2/lot.py
- openprocurement/tender/competitivedialogue/tests/stage2/tender.py
Copy field features, and fix test
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openprocurement/openprocurement.tender.competitivedialogue/70)
> Copy features from first stage to second

- openprocurement/tender/competitivedialogue/tests/stage1/tender.py
- openprocurement/tender/competitivedialogue/utils.py
Fix https://gitter.im/openprocurement/openprocurement.api?at=57e3f9fcc3e7045a306eb95a
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openprocurement/openprocurement.tender.competitivedialogue/72)
> Add check_initial_bids_count when set stand-still

- setup.py
Fix for https://github.com/openprocurement/openprocurement.tender.competitivedialogue/issues/75
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openprocurement/openprocurement.tender.competitivedialogue/76)
> Add api_requires in setup.py

- openprocurement/tender/competitivedialogue/databridge.py
- openprocurement/tender/competitivedialogue/journal_msg_ids.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openprocurement/openprocurement.tender.competitivedialogue/74)
> format logger warning message

- setup.py
fix #77
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openprocurement/openprocurement.tender.competitivedialogue/78)
> add pytz to data bridge requirements

- openprocurement/tender/competitivedialogue/databridge.py
- openprocurement/tender/competitivedialogue/models.py
- openprocurement/tender/competitivedialogue/models_constants.py
- setup.py
fix #77
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openprocurement/openprocurement.tender.competitivedialogue/79)
> add schematics to setup

- openprocurement/tender/competitivedialogue/models.py
- openprocurement/tender/competitivedialogue/tests/stage1/lot.py
- openprocurement/tender/competitivedialogue/tests/stage1/tender.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openprocurement/openprocurement.tender.competitivedialogue/80)
> Hide auction period for lot and tender stage1

- openprocurement/tender/competitivedialogue/models.py
- openprocurement/tender/competitivedialogue/tests/stage1/bid.py
- openprocurement/tender/competitivedialogue/tests/stage1/lot.py
- openprocurement/tender/competitivedialogue/views/stage1/bid.py
Прибрав value з bid та bid.lotValues та пофіксил тести.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openprocurement/openprocurement.tender.competitivedialogue/82)
> Прибрав поле value з пропозицій

- openprocurement/tender/competitivedialogue/databridge.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openprocurement/openprocurement.tender.competitivedialogue/88)
> Логування відповіді ЦБД в мості

- openprocurement/tender/competitivedialogue/databridge.py
Додав фільтрацію для features перед копіюванням на другий етап.
https://github.com/openprocurement/openprocurement.tender.competitivedialogue/issues/87
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openprocurement/openprocurement.tender.competitivedialogue/89)
> copy only actual features

- openprocurement/tender/competitivedialogue/tests/stage1/question.py
- openprocurement/tender/competitivedialogue/tests/stage2/question.py
Кинув на production, тому що на master тягне багато зайвих комітів.
https://github.com/openprocurement/openprocurement.tender.competitivedialogue/issues/91
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openprocurement/openprocurement.tender.competitivedialogue/92)
> Додав поле dateAnswered в questions

- openprocurement/tender/competitivedialogue/models.py
- openprocurement/tender/competitivedialogue/tests/stage2/tender.py
Done https://github.com/openprocurement/openprocurement.tender.competitivedialogue/issues/97
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openprocurement/openprocurement.tender.competitivedialogue/98)
> Зробив "procurementMethod": "selective" на другому етапі значення по замовчуванню

- openprocurement/tender/competitivedialogue/databridge.py
Done https://github.com/openprocurement/openprocurement.tender.competitivedialogue/issues/90
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openprocurement/openprocurement.tender.competitivedialogue/95)
> Add public_tenders_api_server

- openprocurement/tender/competitivedialogue/databridge.py
Логіка копіювання відштовхується від кваліфікацій, але це не правильно ми повинні ще додатково перевіряти, що лот активний.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openprocurement/openprocurement.tender.competitivedialogue/99)
> Копіювати тільки активні лоти

- openprocurement/tender/competitivedialogue/databridge.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openprocurement/openprocurement.tender.competitivedialogue/94)
> after success retry need to continue bridge logic

- buildout.cfg
- openprocurement/tender/competitivedialogue/tests/stage2/bid.py
- openprocurement/tender/competitivedialogue/utils.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openprocurement/openprocurement.tender.competitivedialogue/100)
> Transfer for bid in stage2

- openprocurement/tender/competitivedialogue/databridge.py
Якщо якийсь з воркерів викине exception то ми запишемо його в логи так перезапустимо сервер.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openprocurement/openprocurement.tender.competitivedialogue/106)
> Fix bug databridge

- openprocurement/tender/competitivedialogue/databridge.py
Додав логування для ResourceError, та залишив намагання створити другий етап після 5 невдалих спроб.
https://github.com/openprocurement/openprocurement.tender.competitivedialogue/issues/109
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openprocurement/openprocurement.tender.competitivedialogue/110)
> Stage2 creation retry fix

- buildout.cfg
- openprocurement/tender/competitivedialogue/tests/stage1/bid.py
- openprocurement/tender/competitivedialogue/tests/stage1/complaint.py
- openprocurement/tender/competitivedialogue/tests/stage1/tender.py
- openprocurement/tender/competitivedialogue/tests/stage2/award.py
- openprocurement/tender/competitivedialogue/tests/stage2/bid.py
- openprocurement/tender/competitivedialogue/tests/stage2/complaint.py
- openprocurement/tender/competitivedialogue/tests/stage2/qualification.py
- openprocurement/tender/competitivedialogue/tests/stage2/tender.py
- openprocurement/tender/competitivedialogue/utils.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openprocurement/openprocurement.tender.competitivedialogue/111)
> Add access credentials for stage 2 bid and tests

- openprocurement/tender/competitivedialogue/models.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openprocurement/openprocurement.tender.competitivedialogue/112)
> Add new accreditation field to tender model

- openprocurement/tender/competitivedialogue/tests/stage1/bid.py
- openprocurement/tender/competitivedialogue/tests/stage2/bid.py
- openprocurement/tender/competitivedialogue/views/stage1/bid.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openprocurement/openprocurement.tender.competitivedialogue/115)
> Fix deleted bid can be restored

- openprocurement/tender/competitivedialogue/databridge.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openprocurement/openprocurement.tender.competitivedialogue/118)
> Fix worker died

- openprocurement/tender/competitivedialogue/databridge.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openprocurement/openprocurement.tender.competitivedialogue/123)
> Log when worker die

- openprocurement/tender/competitivedialogue/utils.py
- openprocurement/tender/competitivedialogue/views/stage1/tender.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openprocurement/openprocurement.tender.competitivedialogue/122)
> Fix tender view and utils for relocation

- openprocurement/tender/competitivedialogue/models.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openprocurement/openprocurement.tender.competitivedialogue/124)
> Fix tender model variable name

- docs/source/tutorial.rst
- docs/source/tutorial/tender_stage2_get_token.http
- docs/source/tutorial/tender_stage2_modify_status.http
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openprocurement/openprocurement.tender.competitivedialogue/125)
> Fix stage 2 doc tutorial for credentials

- openprocurement/tender/competitivedialogue/databridge.py
https://github.com/openprocurement/openprocurement.tender.competitivedialogue/issues/114
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openprocurement/openprocurement.tender.competitivedialogue/126)
> Make bridge immortal

- openprocurement/tender/competitivedialogue/databridge.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openprocurement/openprocurement.tender.competitivedialogue/128)
> after 412 need reset cookies

- .gitignore
- openprocurement/tender/competitivedialogue/includeme.py
- openprocurement/tender/competitivedialogue/models.py
- openprocurement/tender/competitivedialogue/subscribers.py
- openprocurement/tender/competitivedialogue/tests/stage2/auction.py
- openprocurement/tender/competitivedialogue/tests/tests.ini
- openprocurement/tender/competitivedialogue/utils.py
- openprocurement/tender/competitivedialogue/views/stage2/tender.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openprocurement/openprocurement.tender.competitivedialogue/134)
> Add tender initialization event handler

- openprocurement/tender/competitivedialogue/utils.py
- openprocurement/tender/competitivedialogue/validation.py
- openprocurement/tender/competitivedialogue/views/stage1/bid.py
- openprocurement/tender/competitivedialogue/views/stage1/tender.py
- openprocurement/tender/competitivedialogue/views/stage2/bid.py
- openprocurement/tender/competitivedialogue/views/stage2/complaint.py
- openprocurement/tender/competitivedialogue/views/stage2/lot.py
- openprocurement/tender/competitivedialogue/views/stage2/tender.py
- openprocurement/tender/competitivedialogue/views/stage2/tender_document.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openprocurement/openprocurement.tender.competitivedialogue/135)
> Validators update

- buildout.cfg
- openprocurement/tender/competitivedialogue/tests/auth.ini
- openprocurement/tender/competitivedialogue/tests/stage2/award.py
- openprocurement/tender/competitivedialogue/tests/stage2/qualification.py
- openprocurement/tender/competitivedialogue/tests/stage2/tender.py
- openprocurement/tender/competitivedialogue/views/stage2/tender_document.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openprocurement/openprocurement.tender.competitivedialogue/136)
> Add edr bot integration

- openprocurement/tender/competitivedialogue/models.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openprocurement/openprocurement.tender.competitivedialogue/141)
> Update imports in models

- openprocurement/tender/competitivedialogue/models.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openprocurement/openprocurement.tender.competitivedialogue/142)
> Update imports in models (SifterListType class)

- docs.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openprocurement/openprocurement.tender.competitivedialogue/143)
> Fix docs py

- openprocurement/tender/competitivedialogue/tests/base.py
- openprocurement/tender/competitivedialogue/tests/stage1/complaint.py
- openprocurement/tender/competitivedialogue/tests/stage1/document.py
- openprocurement/tender/competitivedialogue/tests/stage1/lot.py
- openprocurement/tender/competitivedialogue/tests/stage1/question.py
- openprocurement/tender/competitivedialogue/tests/stage1/tender.py
- openprocurement/tender/competitivedialogue/tests/stage2/award.py
- openprocurement/tender/competitivedialogue/tests/stage2/cancellation.py
- openprocurement/tender/competitivedialogue/tests/stage2/chronograph.py
- openprocurement/tender/competitivedialogue/tests/stage2/contract.py
- openprocurement/tender/competitivedialogue/tests/stage2/document.py
- openprocurement/tender/competitivedialogue/tests/stage2/lot.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openprocurement/openprocurement.tender.competitivedialogue/149)
> move attrs to base.py

- openprocurement/tender/competitivedialogue/tests/base.py
- openprocurement/tender/competitivedialogue/tests/stage2/auction.py
- openprocurement/tender/competitivedialogue/tests/stage2/auction_blanks.py
change statuses identifiers
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openprocurement/openprocurement.tender.competitivedialogue/150)
> add inline comments for statuses

- buildout.cfg
- openprocurement/tender/competitivedialogue/tests/auth.ini
- openprocurement/tender/competitivedialogue/tests/stage2/qualification.py
- openprocurement/tender/competitivedialogue/tests/stage2/tender.py
- openprocurement/tender/competitivedialogue/tests/stage2/tender_blanks.py
- openprocurement/tender/competitivedialogue/views/stage2/tender_document.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openprocurement/openprocurement.tender.competitivedialogue/151)
> A346808780435667 edr integration on refactoring

- openprocurement/tender/competitivedialogue/databridge.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openprocurement/openprocurement.tender.competitivedialogue/152)
> Added logging queues size via extra params

- openprocurement/tender/competitivedialogue/tests/stage2/award.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openprocurement/openprocurement.tender.competitivedialogue/153)
> add missing attributes

- openprocurement/tender/competitivedialogue/tests/stage1/lot.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openprocurement/openprocurement.tender.competitivedialogue/154)
> rename test mixin

- openprocurement/tender/competitivedialogue/tests/stage1/complaint.py
- openprocurement/tender/competitivedialogue/tests/stage2/complaint.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openprocurement/openprocurement.tender.competitivedialogue/155)
> rename blank test

- buildout.cfg
- openprocurement/tender/competitivedialogue/models.py
- openprocurement/tender/competitivedialogue/tests/base.py
- openprocurement/tender/competitivedialogue/tests/stage1/tender_blanks.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openprocurement/openprocurement.tender.competitivedialogue/156)
> A362908003690022 block cpv on refactoring

- openprocurement/tender/competitivedialogue/includeme.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openprocurement/openprocurement.tender.competitivedialogue/133)
> remove print info

- openprocurement/tender/competitivedialogue/tests/base.py
- openprocurement/tender/competitivedialogue/tests/stage1/bid.py
- openprocurement/tender/competitivedialogue/tests/stage1/lot.py
#131
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openprocurement/openprocurement.tender.competitivedialogue/163)
> Fix bids tests

- openprocurement/tender/competitivedialogue/tests/stage1/lot.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openprocurement/openprocurement.tender.competitivedialogue/164)
> a433774298354646 Add test_bids

- openprocurement/tender/competitivedialogue/tests/base.py
- openprocurement/tender/competitivedialogue/tests/stage1/bid.py
- openprocurement/tender/competitivedialogue/tests/stage1/bid_blanks.py
- openprocurement/tender/competitivedialogue/tests/stage1/lot.py
- openprocurement/tender/competitivedialogue/tests/stage1/lot_blanks.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openprocurement/openprocurement.tender.competitivedialogue/165)
> A 435874919170362 bids count

- buildout.cfg
- openprocurement/tender/competitivedialogue/tests/stage2/tender.py
- openprocurement/tender/competitivedialogue/tests/stage2/tender_blanks.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openprocurement/openprocurement.tender.competitivedialogue/169)
> A448207762065014 funders

- buildout.cfg
- docs/source/complaints.rst
- openprocurement/tender/competitivedialogue/tests/stage2/qualification.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openprocurement/openprocurement.tender.competitivedialogue/170)
> reviewer status transition stopping->satisfied, panding->stopped

- openprocurement/tender/competitivedialogue/tests/stage2/auction.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openprocurement/openprocurement.tender.competitivedialogue/172)
> Add features test to competitive dialogue

- setup.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openprocurement/openprocurement.tender.competitivedialogue/174)
> A563879808284502 disable 999999 9 additional classification required
